# Site wide configuration

title: Nemo Mobile UX team
description: This is the team site for the Nemo Mobile user experience, including documentation to latest software and components
logo: nemo-logo.svg
teaser: nemo-logo.svg
locale:
url: https://nemomobile-ux.github.io
baseurl: ""

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /pages/:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Site owner
owner:
  name: Nemo Mobile
  email:
  twitter: NemoMobile
  bio:
  avatar: nemo-logo-small.png # 160x160 px image for author byline
disqus-shortname:

social:
  twitter: https://twitter.com/nemomobile
  github: https://github.com/nemomobile
  telegram: https://telegram.me/nemomobile
  irc: irc://irc.freenode.net:+6697/nemomobile
  matrix: https://matrix.to/#/#nemomobile:matrix.org

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
