version: '3'
services:
  jekyll:
      image: ruby:latest
      user: $UID
      command: bash -c "gem install jekyll && bundle install && bundle exec jekyll serve --watch --incremental --config _config.yml --host 0.0.0.0"
      ports:
          - 4000:4000
      volumes:
        - .:/srv/jekyll
#        - ./vendor/bundle:/usr/local/bundle
      working_dir: /srv/jekyll